/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var tensorflow_core_protobuf_trackable_object_graph_pb = require('../../../tensorflow/core/protobuf/trackable_object_graph_pb.js');
goog.object.extend(proto, tensorflow_core_protobuf_trackable_object_graph_pb);
var tensorflow_core_protobuf_struct_pb = require('../../../tensorflow/core/protobuf/struct_pb.js');
goog.object.extend(proto, tensorflow_core_protobuf_struct_pb);
var tensorflow_core_framework_tensor_shape_pb = require('../../../tensorflow/core/framework/tensor_shape_pb.js');
goog.object.extend(proto, tensorflow_core_framework_tensor_shape_pb);
var tensorflow_core_framework_types_pb = require('../../../tensorflow/core/framework/types_pb.js');
goog.object.extend(proto, tensorflow_core_framework_types_pb);
var tensorflow_core_framework_versions_pb = require('../../../tensorflow/core/framework/versions_pb.js');
goog.object.extend(proto, tensorflow_core_framework_versions_pb);
var tensorflow_core_framework_variable_pb = require('../../../tensorflow/core/framework/variable_pb.js');
goog.object.extend(proto, tensorflow_core_framework_variable_pb);
goog.exportSymbol('proto.tensorflow.FunctionSpec', null, global);
goog.exportSymbol('proto.tensorflow.SavedAsset', null, global);
goog.exportSymbol('proto.tensorflow.SavedBareConcreteFunction', null, global);
goog.exportSymbol('proto.tensorflow.SavedConcreteFunction', null, global);
goog.exportSymbol('proto.tensorflow.SavedConstant', null, global);
goog.exportSymbol('proto.tensorflow.SavedFunction', null, global);
goog.exportSymbol('proto.tensorflow.SavedObject', null, global);
goog.exportSymbol('proto.tensorflow.SavedObjectGraph', null, global);
goog.exportSymbol('proto.tensorflow.SavedResource', null, global);
goog.exportSymbol('proto.tensorflow.SavedUserObject', null, global);
goog.exportSymbol('proto.tensorflow.SavedVariable', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedObjectGraph = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.SavedObjectGraph.repeatedFields_, null);
};
goog.inherits(proto.tensorflow.SavedObjectGraph, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedObjectGraph.displayName = 'proto.tensorflow.SavedObjectGraph';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.SavedObjectGraph.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedObjectGraph.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedObjectGraph.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedObjectGraph} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedObjectGraph.toObject = function(includeInstance, msg) {
  var f, obj = {
    nodesList: jspb.Message.toObjectList(msg.getNodesList(),
    proto.tensorflow.SavedObject.toObject, includeInstance),
    concreteFunctionsMap: (f = msg.getConcreteFunctionsMap()) ? f.toObject(includeInstance, proto.tensorflow.SavedConcreteFunction.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedObjectGraph}
 */
proto.tensorflow.SavedObjectGraph.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedObjectGraph;
  return proto.tensorflow.SavedObjectGraph.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedObjectGraph} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedObjectGraph}
 */
proto.tensorflow.SavedObjectGraph.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tensorflow.SavedObject;
      reader.readMessage(value,proto.tensorflow.SavedObject.deserializeBinaryFromReader);
      msg.addNodes(value);
      break;
    case 2:
      var value = msg.getConcreteFunctionsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.tensorflow.SavedConcreteFunction.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedObjectGraph.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedObjectGraph.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedObjectGraph} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedObjectGraph.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.tensorflow.SavedObject.serializeBinaryToWriter
    );
  }
  f = message.getConcreteFunctionsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.tensorflow.SavedConcreteFunction.serializeBinaryToWriter);
  }
};


/**
 * repeated SavedObject nodes = 1;
 * @return {!Array<!proto.tensorflow.SavedObject>}
 */
proto.tensorflow.SavedObjectGraph.prototype.getNodesList = function() {
  return /** @type{!Array<!proto.tensorflow.SavedObject>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tensorflow.SavedObject, 1));
};


/** @param {!Array<!proto.tensorflow.SavedObject>} value */
proto.tensorflow.SavedObjectGraph.prototype.setNodesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.tensorflow.SavedObject=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tensorflow.SavedObject}
 */
proto.tensorflow.SavedObjectGraph.prototype.addNodes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.tensorflow.SavedObject, opt_index);
};


proto.tensorflow.SavedObjectGraph.prototype.clearNodesList = function() {
  this.setNodesList([]);
};


/**
 * map<string, SavedConcreteFunction> concrete_functions = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.tensorflow.SavedConcreteFunction>}
 */
proto.tensorflow.SavedObjectGraph.prototype.getConcreteFunctionsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.tensorflow.SavedConcreteFunction>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.tensorflow.SavedConcreteFunction));
};


proto.tensorflow.SavedObjectGraph.prototype.clearConcreteFunctionsMap = function() {
  this.getConcreteFunctionsMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedObject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.SavedObject.repeatedFields_, proto.tensorflow.SavedObject.oneofGroups_);
};
goog.inherits(proto.tensorflow.SavedObject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedObject.displayName = 'proto.tensorflow.SavedObject';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.SavedObject.repeatedFields_ = [1,3];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tensorflow.SavedObject.oneofGroups_ = [[4,5,6,7,8,9,10]];

/**
 * @enum {number}
 */
proto.tensorflow.SavedObject.KindCase = {
  KIND_NOT_SET: 0,
  USER_OBJECT: 4,
  ASSET: 5,
  FUNCTION: 6,
  VARIABLE: 7,
  BARE_CONCRETE_FUNCTION: 8,
  CONSTANT: 9,
  RESOURCE: 10
};

/**
 * @return {proto.tensorflow.SavedObject.KindCase}
 */
proto.tensorflow.SavedObject.prototype.getKindCase = function() {
  return /** @type {proto.tensorflow.SavedObject.KindCase} */(jspb.Message.computeOneofCase(this, proto.tensorflow.SavedObject.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedObject.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedObject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedObject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedObject.toObject = function(includeInstance, msg) {
  var f, obj = {
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.ObjectReference.toObject, includeInstance),
    slotVariablesList: jspb.Message.toObjectList(msg.getSlotVariablesList(),
    tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.SlotVariableReference.toObject, includeInstance),
    userObject: (f = msg.getUserObject()) && proto.tensorflow.SavedUserObject.toObject(includeInstance, f),
    asset: (f = msg.getAsset()) && proto.tensorflow.SavedAsset.toObject(includeInstance, f),
    pb_function: (f = msg.getFunction()) && proto.tensorflow.SavedFunction.toObject(includeInstance, f),
    variable: (f = msg.getVariable()) && proto.tensorflow.SavedVariable.toObject(includeInstance, f),
    bareConcreteFunction: (f = msg.getBareConcreteFunction()) && proto.tensorflow.SavedBareConcreteFunction.toObject(includeInstance, f),
    constant: (f = msg.getConstant()) && proto.tensorflow.SavedConstant.toObject(includeInstance, f),
    resource: (f = msg.getResource()) && proto.tensorflow.SavedResource.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedObject}
 */
proto.tensorflow.SavedObject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedObject;
  return proto.tensorflow.SavedObject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedObject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedObject}
 */
proto.tensorflow.SavedObject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.ObjectReference;
      reader.readMessage(value,tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.ObjectReference.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    case 3:
      var value = new tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.SlotVariableReference;
      reader.readMessage(value,tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.SlotVariableReference.deserializeBinaryFromReader);
      msg.addSlotVariables(value);
      break;
    case 4:
      var value = new proto.tensorflow.SavedUserObject;
      reader.readMessage(value,proto.tensorflow.SavedUserObject.deserializeBinaryFromReader);
      msg.setUserObject(value);
      break;
    case 5:
      var value = new proto.tensorflow.SavedAsset;
      reader.readMessage(value,proto.tensorflow.SavedAsset.deserializeBinaryFromReader);
      msg.setAsset(value);
      break;
    case 6:
      var value = new proto.tensorflow.SavedFunction;
      reader.readMessage(value,proto.tensorflow.SavedFunction.deserializeBinaryFromReader);
      msg.setFunction(value);
      break;
    case 7:
      var value = new proto.tensorflow.SavedVariable;
      reader.readMessage(value,proto.tensorflow.SavedVariable.deserializeBinaryFromReader);
      msg.setVariable(value);
      break;
    case 8:
      var value = new proto.tensorflow.SavedBareConcreteFunction;
      reader.readMessage(value,proto.tensorflow.SavedBareConcreteFunction.deserializeBinaryFromReader);
      msg.setBareConcreteFunction(value);
      break;
    case 9:
      var value = new proto.tensorflow.SavedConstant;
      reader.readMessage(value,proto.tensorflow.SavedConstant.deserializeBinaryFromReader);
      msg.setConstant(value);
      break;
    case 10:
      var value = new proto.tensorflow.SavedResource;
      reader.readMessage(value,proto.tensorflow.SavedResource.deserializeBinaryFromReader);
      msg.setResource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedObject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedObject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedObject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedObject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.ObjectReference.serializeBinaryToWriter
    );
  }
  f = message.getSlotVariablesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.SlotVariableReference.serializeBinaryToWriter
    );
  }
  f = message.getUserObject();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.tensorflow.SavedUserObject.serializeBinaryToWriter
    );
  }
  f = message.getAsset();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.tensorflow.SavedAsset.serializeBinaryToWriter
    );
  }
  f = message.getFunction();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.tensorflow.SavedFunction.serializeBinaryToWriter
    );
  }
  f = message.getVariable();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.tensorflow.SavedVariable.serializeBinaryToWriter
    );
  }
  f = message.getBareConcreteFunction();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.tensorflow.SavedBareConcreteFunction.serializeBinaryToWriter
    );
  }
  f = message.getConstant();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.tensorflow.SavedConstant.serializeBinaryToWriter
    );
  }
  f = message.getResource();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.tensorflow.SavedResource.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TrackableObjectGraph.TrackableObject.ObjectReference children = 1;
 * @return {!Array<!proto.tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference>}
 */
proto.tensorflow.SavedObject.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference>} */ (
    jspb.Message.getRepeatedWrapperField(this, tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.ObjectReference, 1));
};


/** @param {!Array<!proto.tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference>} value */
proto.tensorflow.SavedObject.prototype.setChildrenList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference}
 */
proto.tensorflow.SavedObject.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference, opt_index);
};


proto.tensorflow.SavedObject.prototype.clearChildrenList = function() {
  this.setChildrenList([]);
};


/**
 * repeated TrackableObjectGraph.TrackableObject.SlotVariableReference slot_variables = 3;
 * @return {!Array<!proto.tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference>}
 */
proto.tensorflow.SavedObject.prototype.getSlotVariablesList = function() {
  return /** @type{!Array<!proto.tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference>} */ (
    jspb.Message.getRepeatedWrapperField(this, tensorflow_core_protobuf_trackable_object_graph_pb.TrackableObjectGraph.TrackableObject.SlotVariableReference, 3));
};


/** @param {!Array<!proto.tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference>} value */
proto.tensorflow.SavedObject.prototype.setSlotVariablesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference}
 */
proto.tensorflow.SavedObject.prototype.addSlotVariables = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference, opt_index);
};


proto.tensorflow.SavedObject.prototype.clearSlotVariablesList = function() {
  this.setSlotVariablesList([]);
};


/**
 * optional SavedUserObject user_object = 4;
 * @return {?proto.tensorflow.SavedUserObject}
 */
proto.tensorflow.SavedObject.prototype.getUserObject = function() {
  return /** @type{?proto.tensorflow.SavedUserObject} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.SavedUserObject, 4));
};


/** @param {?proto.tensorflow.SavedUserObject|undefined} value */
proto.tensorflow.SavedObject.prototype.setUserObject = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.tensorflow.SavedObject.oneofGroups_[0], value);
};


proto.tensorflow.SavedObject.prototype.clearUserObject = function() {
  this.setUserObject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedObject.prototype.hasUserObject = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional SavedAsset asset = 5;
 * @return {?proto.tensorflow.SavedAsset}
 */
proto.tensorflow.SavedObject.prototype.getAsset = function() {
  return /** @type{?proto.tensorflow.SavedAsset} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.SavedAsset, 5));
};


/** @param {?proto.tensorflow.SavedAsset|undefined} value */
proto.tensorflow.SavedObject.prototype.setAsset = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.tensorflow.SavedObject.oneofGroups_[0], value);
};


proto.tensorflow.SavedObject.prototype.clearAsset = function() {
  this.setAsset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedObject.prototype.hasAsset = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional SavedFunction function = 6;
 * @return {?proto.tensorflow.SavedFunction}
 */
proto.tensorflow.SavedObject.prototype.getFunction = function() {
  return /** @type{?proto.tensorflow.SavedFunction} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.SavedFunction, 6));
};


/** @param {?proto.tensorflow.SavedFunction|undefined} value */
proto.tensorflow.SavedObject.prototype.setFunction = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.tensorflow.SavedObject.oneofGroups_[0], value);
};


proto.tensorflow.SavedObject.prototype.clearFunction = function() {
  this.setFunction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedObject.prototype.hasFunction = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional SavedVariable variable = 7;
 * @return {?proto.tensorflow.SavedVariable}
 */
proto.tensorflow.SavedObject.prototype.getVariable = function() {
  return /** @type{?proto.tensorflow.SavedVariable} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.SavedVariable, 7));
};


/** @param {?proto.tensorflow.SavedVariable|undefined} value */
proto.tensorflow.SavedObject.prototype.setVariable = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.tensorflow.SavedObject.oneofGroups_[0], value);
};


proto.tensorflow.SavedObject.prototype.clearVariable = function() {
  this.setVariable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedObject.prototype.hasVariable = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional SavedBareConcreteFunction bare_concrete_function = 8;
 * @return {?proto.tensorflow.SavedBareConcreteFunction}
 */
proto.tensorflow.SavedObject.prototype.getBareConcreteFunction = function() {
  return /** @type{?proto.tensorflow.SavedBareConcreteFunction} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.SavedBareConcreteFunction, 8));
};


/** @param {?proto.tensorflow.SavedBareConcreteFunction|undefined} value */
proto.tensorflow.SavedObject.prototype.setBareConcreteFunction = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.tensorflow.SavedObject.oneofGroups_[0], value);
};


proto.tensorflow.SavedObject.prototype.clearBareConcreteFunction = function() {
  this.setBareConcreteFunction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedObject.prototype.hasBareConcreteFunction = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional SavedConstant constant = 9;
 * @return {?proto.tensorflow.SavedConstant}
 */
proto.tensorflow.SavedObject.prototype.getConstant = function() {
  return /** @type{?proto.tensorflow.SavedConstant} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.SavedConstant, 9));
};


/** @param {?proto.tensorflow.SavedConstant|undefined} value */
proto.tensorflow.SavedObject.prototype.setConstant = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.tensorflow.SavedObject.oneofGroups_[0], value);
};


proto.tensorflow.SavedObject.prototype.clearConstant = function() {
  this.setConstant(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedObject.prototype.hasConstant = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional SavedResource resource = 10;
 * @return {?proto.tensorflow.SavedResource}
 */
proto.tensorflow.SavedObject.prototype.getResource = function() {
  return /** @type{?proto.tensorflow.SavedResource} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.SavedResource, 10));
};


/** @param {?proto.tensorflow.SavedResource|undefined} value */
proto.tensorflow.SavedObject.prototype.setResource = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.tensorflow.SavedObject.oneofGroups_[0], value);
};


proto.tensorflow.SavedObject.prototype.clearResource = function() {
  this.setResource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedObject.prototype.hasResource = function() {
  return jspb.Message.getField(this, 10) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedUserObject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.SavedUserObject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedUserObject.displayName = 'proto.tensorflow.SavedUserObject';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedUserObject.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedUserObject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedUserObject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedUserObject.toObject = function(includeInstance, msg) {
  var f, obj = {
    identifier: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: (f = msg.getVersion()) && tensorflow_core_framework_versions_pb.VersionDef.toObject(includeInstance, f),
    metadata: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedUserObject}
 */
proto.tensorflow.SavedUserObject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedUserObject;
  return proto.tensorflow.SavedUserObject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedUserObject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedUserObject}
 */
proto.tensorflow.SavedUserObject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentifier(value);
      break;
    case 2:
      var value = new tensorflow_core_framework_versions_pb.VersionDef;
      reader.readMessage(value,tensorflow_core_framework_versions_pb.VersionDef.deserializeBinaryFromReader);
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedUserObject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedUserObject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedUserObject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedUserObject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentifier();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      tensorflow_core_framework_versions_pb.VersionDef.serializeBinaryToWriter
    );
  }
  f = message.getMetadata();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string identifier = 1;
 * @return {string}
 */
proto.tensorflow.SavedUserObject.prototype.getIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.tensorflow.SavedUserObject.prototype.setIdentifier = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional VersionDef version = 2;
 * @return {?proto.tensorflow.VersionDef}
 */
proto.tensorflow.SavedUserObject.prototype.getVersion = function() {
  return /** @type{?proto.tensorflow.VersionDef} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_framework_versions_pb.VersionDef, 2));
};


/** @param {?proto.tensorflow.VersionDef|undefined} value */
proto.tensorflow.SavedUserObject.prototype.setVersion = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.tensorflow.SavedUserObject.prototype.clearVersion = function() {
  this.setVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedUserObject.prototype.hasVersion = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string metadata = 3;
 * @return {string}
 */
proto.tensorflow.SavedUserObject.prototype.getMetadata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.tensorflow.SavedUserObject.prototype.setMetadata = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedAsset = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.SavedAsset, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedAsset.displayName = 'proto.tensorflow.SavedAsset';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedAsset.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedAsset.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedAsset} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedAsset.toObject = function(includeInstance, msg) {
  var f, obj = {
    assetFileDefIndex: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedAsset}
 */
proto.tensorflow.SavedAsset.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedAsset;
  return proto.tensorflow.SavedAsset.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedAsset} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedAsset}
 */
proto.tensorflow.SavedAsset.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAssetFileDefIndex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedAsset.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedAsset.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedAsset} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedAsset.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAssetFileDefIndex();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 asset_file_def_index = 1;
 * @return {number}
 */
proto.tensorflow.SavedAsset.prototype.getAssetFileDefIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.tensorflow.SavedAsset.prototype.setAssetFileDefIndex = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedFunction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.SavedFunction.repeatedFields_, null);
};
goog.inherits(proto.tensorflow.SavedFunction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedFunction.displayName = 'proto.tensorflow.SavedFunction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.SavedFunction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedFunction.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedFunction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedFunction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedFunction.toObject = function(includeInstance, msg) {
  var f, obj = {
    concreteFunctionsList: jspb.Message.getRepeatedField(msg, 1),
    functionSpec: (f = msg.getFunctionSpec()) && proto.tensorflow.FunctionSpec.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedFunction}
 */
proto.tensorflow.SavedFunction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedFunction;
  return proto.tensorflow.SavedFunction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedFunction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedFunction}
 */
proto.tensorflow.SavedFunction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addConcreteFunctions(value);
      break;
    case 2:
      var value = new proto.tensorflow.FunctionSpec;
      reader.readMessage(value,proto.tensorflow.FunctionSpec.deserializeBinaryFromReader);
      msg.setFunctionSpec(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedFunction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedFunction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedFunction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedFunction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConcreteFunctionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getFunctionSpec();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.tensorflow.FunctionSpec.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string concrete_functions = 1;
 * @return {!Array<string>}
 */
proto.tensorflow.SavedFunction.prototype.getConcreteFunctionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.tensorflow.SavedFunction.prototype.setConcreteFunctionsList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.tensorflow.SavedFunction.prototype.addConcreteFunctions = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.tensorflow.SavedFunction.prototype.clearConcreteFunctionsList = function() {
  this.setConcreteFunctionsList([]);
};


/**
 * optional FunctionSpec function_spec = 2;
 * @return {?proto.tensorflow.FunctionSpec}
 */
proto.tensorflow.SavedFunction.prototype.getFunctionSpec = function() {
  return /** @type{?proto.tensorflow.FunctionSpec} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.FunctionSpec, 2));
};


/** @param {?proto.tensorflow.FunctionSpec|undefined} value */
proto.tensorflow.SavedFunction.prototype.setFunctionSpec = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.tensorflow.SavedFunction.prototype.clearFunctionSpec = function() {
  this.setFunctionSpec(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedFunction.prototype.hasFunctionSpec = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedConcreteFunction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.SavedConcreteFunction.repeatedFields_, null);
};
goog.inherits(proto.tensorflow.SavedConcreteFunction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedConcreteFunction.displayName = 'proto.tensorflow.SavedConcreteFunction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.SavedConcreteFunction.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedConcreteFunction.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedConcreteFunction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedConcreteFunction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedConcreteFunction.toObject = function(includeInstance, msg) {
  var f, obj = {
    boundInputsList: jspb.Message.getRepeatedField(msg, 2),
    canonicalizedInputSignature: (f = msg.getCanonicalizedInputSignature()) && tensorflow_core_protobuf_struct_pb.StructuredValue.toObject(includeInstance, f),
    outputSignature: (f = msg.getOutputSignature()) && tensorflow_core_protobuf_struct_pb.StructuredValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedConcreteFunction}
 */
proto.tensorflow.SavedConcreteFunction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedConcreteFunction;
  return proto.tensorflow.SavedConcreteFunction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedConcreteFunction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedConcreteFunction}
 */
proto.tensorflow.SavedConcreteFunction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setBoundInputsList(value);
      break;
    case 3:
      var value = new tensorflow_core_protobuf_struct_pb.StructuredValue;
      reader.readMessage(value,tensorflow_core_protobuf_struct_pb.StructuredValue.deserializeBinaryFromReader);
      msg.setCanonicalizedInputSignature(value);
      break;
    case 4:
      var value = new tensorflow_core_protobuf_struct_pb.StructuredValue;
      reader.readMessage(value,tensorflow_core_protobuf_struct_pb.StructuredValue.deserializeBinaryFromReader);
      msg.setOutputSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedConcreteFunction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedConcreteFunction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedConcreteFunction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedConcreteFunction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBoundInputsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
  f = message.getCanonicalizedInputSignature();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      tensorflow_core_protobuf_struct_pb.StructuredValue.serializeBinaryToWriter
    );
  }
  f = message.getOutputSignature();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      tensorflow_core_protobuf_struct_pb.StructuredValue.serializeBinaryToWriter
    );
  }
};


/**
 * repeated int32 bound_inputs = 2;
 * @return {!Array<number>}
 */
proto.tensorflow.SavedConcreteFunction.prototype.getBoundInputsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<number>} value */
proto.tensorflow.SavedConcreteFunction.prototype.setBoundInputsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.tensorflow.SavedConcreteFunction.prototype.addBoundInputs = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.tensorflow.SavedConcreteFunction.prototype.clearBoundInputsList = function() {
  this.setBoundInputsList([]);
};


/**
 * optional StructuredValue canonicalized_input_signature = 3;
 * @return {?proto.tensorflow.StructuredValue}
 */
proto.tensorflow.SavedConcreteFunction.prototype.getCanonicalizedInputSignature = function() {
  return /** @type{?proto.tensorflow.StructuredValue} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_struct_pb.StructuredValue, 3));
};


/** @param {?proto.tensorflow.StructuredValue|undefined} value */
proto.tensorflow.SavedConcreteFunction.prototype.setCanonicalizedInputSignature = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.tensorflow.SavedConcreteFunction.prototype.clearCanonicalizedInputSignature = function() {
  this.setCanonicalizedInputSignature(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedConcreteFunction.prototype.hasCanonicalizedInputSignature = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional StructuredValue output_signature = 4;
 * @return {?proto.tensorflow.StructuredValue}
 */
proto.tensorflow.SavedConcreteFunction.prototype.getOutputSignature = function() {
  return /** @type{?proto.tensorflow.StructuredValue} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_struct_pb.StructuredValue, 4));
};


/** @param {?proto.tensorflow.StructuredValue|undefined} value */
proto.tensorflow.SavedConcreteFunction.prototype.setOutputSignature = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.tensorflow.SavedConcreteFunction.prototype.clearOutputSignature = function() {
  this.setOutputSignature(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedConcreteFunction.prototype.hasOutputSignature = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedBareConcreteFunction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.SavedBareConcreteFunction.repeatedFields_, null);
};
goog.inherits(proto.tensorflow.SavedBareConcreteFunction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedBareConcreteFunction.displayName = 'proto.tensorflow.SavedBareConcreteFunction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.SavedBareConcreteFunction.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedBareConcreteFunction.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedBareConcreteFunction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedBareConcreteFunction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedBareConcreteFunction.toObject = function(includeInstance, msg) {
  var f, obj = {
    concreteFunctionName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    argumentKeywordsList: jspb.Message.getRepeatedField(msg, 2),
    allowedPositionalArguments: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedBareConcreteFunction}
 */
proto.tensorflow.SavedBareConcreteFunction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedBareConcreteFunction;
  return proto.tensorflow.SavedBareConcreteFunction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedBareConcreteFunction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedBareConcreteFunction}
 */
proto.tensorflow.SavedBareConcreteFunction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConcreteFunctionName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addArgumentKeywords(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAllowedPositionalArguments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedBareConcreteFunction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedBareConcreteFunction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedBareConcreteFunction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedBareConcreteFunction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConcreteFunctionName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getArgumentKeywordsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getAllowedPositionalArguments();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string concrete_function_name = 1;
 * @return {string}
 */
proto.tensorflow.SavedBareConcreteFunction.prototype.getConcreteFunctionName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.tensorflow.SavedBareConcreteFunction.prototype.setConcreteFunctionName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string argument_keywords = 2;
 * @return {!Array<string>}
 */
proto.tensorflow.SavedBareConcreteFunction.prototype.getArgumentKeywordsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.tensorflow.SavedBareConcreteFunction.prototype.setArgumentKeywordsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.tensorflow.SavedBareConcreteFunction.prototype.addArgumentKeywords = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.tensorflow.SavedBareConcreteFunction.prototype.clearArgumentKeywordsList = function() {
  this.setArgumentKeywordsList([]);
};


/**
 * optional int64 allowed_positional_arguments = 3;
 * @return {number}
 */
proto.tensorflow.SavedBareConcreteFunction.prototype.getAllowedPositionalArguments = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.tensorflow.SavedBareConcreteFunction.prototype.setAllowedPositionalArguments = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedConstant = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.SavedConstant, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedConstant.displayName = 'proto.tensorflow.SavedConstant';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedConstant.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedConstant.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedConstant} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedConstant.toObject = function(includeInstance, msg) {
  var f, obj = {
    operation: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedConstant}
 */
proto.tensorflow.SavedConstant.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedConstant;
  return proto.tensorflow.SavedConstant.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedConstant} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedConstant}
 */
proto.tensorflow.SavedConstant.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedConstant.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedConstant.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedConstant} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedConstant.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperation();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string operation = 1;
 * @return {string}
 */
proto.tensorflow.SavedConstant.prototype.getOperation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.tensorflow.SavedConstant.prototype.setOperation = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedVariable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.SavedVariable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedVariable.displayName = 'proto.tensorflow.SavedVariable';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedVariable.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedVariable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedVariable} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedVariable.toObject = function(includeInstance, msg) {
  var f, obj = {
    dtype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    shape: (f = msg.getShape()) && tensorflow_core_framework_tensor_shape_pb.TensorShapeProto.toObject(includeInstance, f),
    trainable: jspb.Message.getFieldWithDefault(msg, 3, false),
    synchronization: jspb.Message.getFieldWithDefault(msg, 4, 0),
    aggregation: jspb.Message.getFieldWithDefault(msg, 5, 0),
    name: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedVariable}
 */
proto.tensorflow.SavedVariable.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedVariable;
  return proto.tensorflow.SavedVariable.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedVariable} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedVariable}
 */
proto.tensorflow.SavedVariable.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tensorflow.DataType} */ (reader.readEnum());
      msg.setDtype(value);
      break;
    case 2:
      var value = new tensorflow_core_framework_tensor_shape_pb.TensorShapeProto;
      reader.readMessage(value,tensorflow_core_framework_tensor_shape_pb.TensorShapeProto.deserializeBinaryFromReader);
      msg.setShape(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTrainable(value);
      break;
    case 4:
      var value = /** @type {!proto.tensorflow.VariableSynchronization} */ (reader.readEnum());
      msg.setSynchronization(value);
      break;
    case 5:
      var value = /** @type {!proto.tensorflow.VariableAggregation} */ (reader.readEnum());
      msg.setAggregation(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedVariable.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedVariable.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedVariable} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedVariable.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDtype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getShape();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      tensorflow_core_framework_tensor_shape_pb.TensorShapeProto.serializeBinaryToWriter
    );
  }
  f = message.getTrainable();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getSynchronization();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getAggregation();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional DataType dtype = 1;
 * @return {!proto.tensorflow.DataType}
 */
proto.tensorflow.SavedVariable.prototype.getDtype = function() {
  return /** @type {!proto.tensorflow.DataType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.tensorflow.DataType} value */
proto.tensorflow.SavedVariable.prototype.setDtype = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional TensorShapeProto shape = 2;
 * @return {?proto.tensorflow.TensorShapeProto}
 */
proto.tensorflow.SavedVariable.prototype.getShape = function() {
  return /** @type{?proto.tensorflow.TensorShapeProto} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_framework_tensor_shape_pb.TensorShapeProto, 2));
};


/** @param {?proto.tensorflow.TensorShapeProto|undefined} value */
proto.tensorflow.SavedVariable.prototype.setShape = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.tensorflow.SavedVariable.prototype.clearShape = function() {
  this.setShape(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.SavedVariable.prototype.hasShape = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool trainable = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.tensorflow.SavedVariable.prototype.getTrainable = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.tensorflow.SavedVariable.prototype.setTrainable = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional VariableSynchronization synchronization = 4;
 * @return {!proto.tensorflow.VariableSynchronization}
 */
proto.tensorflow.SavedVariable.prototype.getSynchronization = function() {
  return /** @type {!proto.tensorflow.VariableSynchronization} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.tensorflow.VariableSynchronization} value */
proto.tensorflow.SavedVariable.prototype.setSynchronization = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional VariableAggregation aggregation = 5;
 * @return {!proto.tensorflow.VariableAggregation}
 */
proto.tensorflow.SavedVariable.prototype.getAggregation = function() {
  return /** @type {!proto.tensorflow.VariableAggregation} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.tensorflow.VariableAggregation} value */
proto.tensorflow.SavedVariable.prototype.setAggregation = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string name = 6;
 * @return {string}
 */
proto.tensorflow.SavedVariable.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.tensorflow.SavedVariable.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.FunctionSpec = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.FunctionSpec, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.FunctionSpec.displayName = 'proto.tensorflow.FunctionSpec';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.FunctionSpec.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.FunctionSpec.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.FunctionSpec} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.FunctionSpec.toObject = function(includeInstance, msg) {
  var f, obj = {
    fullargspec: (f = msg.getFullargspec()) && tensorflow_core_protobuf_struct_pb.StructuredValue.toObject(includeInstance, f),
    isMethod: jspb.Message.getFieldWithDefault(msg, 2, false),
    inputSignature: (f = msg.getInputSignature()) && tensorflow_core_protobuf_struct_pb.StructuredValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.FunctionSpec}
 */
proto.tensorflow.FunctionSpec.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.FunctionSpec;
  return proto.tensorflow.FunctionSpec.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.FunctionSpec} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.FunctionSpec}
 */
proto.tensorflow.FunctionSpec.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tensorflow_core_protobuf_struct_pb.StructuredValue;
      reader.readMessage(value,tensorflow_core_protobuf_struct_pb.StructuredValue.deserializeBinaryFromReader);
      msg.setFullargspec(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsMethod(value);
      break;
    case 5:
      var value = new tensorflow_core_protobuf_struct_pb.StructuredValue;
      reader.readMessage(value,tensorflow_core_protobuf_struct_pb.StructuredValue.deserializeBinaryFromReader);
      msg.setInputSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.FunctionSpec.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.FunctionSpec.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.FunctionSpec} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.FunctionSpec.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFullargspec();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      tensorflow_core_protobuf_struct_pb.StructuredValue.serializeBinaryToWriter
    );
  }
  f = message.getIsMethod();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getInputSignature();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      tensorflow_core_protobuf_struct_pb.StructuredValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional StructuredValue fullargspec = 1;
 * @return {?proto.tensorflow.StructuredValue}
 */
proto.tensorflow.FunctionSpec.prototype.getFullargspec = function() {
  return /** @type{?proto.tensorflow.StructuredValue} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_struct_pb.StructuredValue, 1));
};


/** @param {?proto.tensorflow.StructuredValue|undefined} value */
proto.tensorflow.FunctionSpec.prototype.setFullargspec = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.tensorflow.FunctionSpec.prototype.clearFullargspec = function() {
  this.setFullargspec(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.FunctionSpec.prototype.hasFullargspec = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool is_method = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.tensorflow.FunctionSpec.prototype.getIsMethod = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.tensorflow.FunctionSpec.prototype.setIsMethod = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional StructuredValue input_signature = 5;
 * @return {?proto.tensorflow.StructuredValue}
 */
proto.tensorflow.FunctionSpec.prototype.getInputSignature = function() {
  return /** @type{?proto.tensorflow.StructuredValue} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_struct_pb.StructuredValue, 5));
};


/** @param {?proto.tensorflow.StructuredValue|undefined} value */
proto.tensorflow.FunctionSpec.prototype.setInputSignature = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.tensorflow.FunctionSpec.prototype.clearInputSignature = function() {
  this.setInputSignature(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.FunctionSpec.prototype.hasInputSignature = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.SavedResource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.SavedResource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.SavedResource.displayName = 'proto.tensorflow.SavedResource';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.SavedResource.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.SavedResource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.SavedResource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedResource.toObject = function(includeInstance, msg) {
  var f, obj = {
    device: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.SavedResource}
 */
proto.tensorflow.SavedResource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.SavedResource;
  return proto.tensorflow.SavedResource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.SavedResource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.SavedResource}
 */
proto.tensorflow.SavedResource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.SavedResource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.SavedResource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.SavedResource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.SavedResource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevice();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string device = 1;
 * @return {string}
 */
proto.tensorflow.SavedResource.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.tensorflow.SavedResource.prototype.setDevice = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.tensorflow);
